apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nginx.yaml
patchesJson6902:
- patch: |-
    - op: add
      path: /metadata/labels/tool
      value: kustomize
  target:
    group: apps
    kind: Deployment
    name: nginx
    version: v1
